### ISSUE TITLE
求助在群晖docker界面上如何设置

### ISSUE THREAD

**Issue by jythldgz** [keli/docker-xiazaibao-xware#3]
小白不会用命令行，求教大侠如何直接在群晖docker的ui上设置。--mac-address 00:1A:2B:3C:4D:5E \  --privileged \ 设置mac地址和提升权限这两个命令在界面上如何设置，求教。
![image](https://user-images.githubusercontent.com/45750997/49954923-9358ef80-ff3c-11e8-8198-08df6da84a21.png)

**Comment by jythldgz** [comment]
求指教

**Comment by suifengsh** [comment]
同求作者指导，是不是只能在命令行中启动呢？docker设置界面不知道如何设置。

**Comment by keli** [comment]
界面里好像没法设置mac地址

**Comment by suifengsh** [comment]
谢谢keli，已经会用了，用您提供的命令行实现的。
