### ISSUE TITLE
运行成功 APP一直是离线

### ISSUE THREAD

**Issue by Poxiaoz** [keli/docker-xiazaibao-xware#5]

**Comment by suifengsh** [comment]
我也是这样，作者也是这样吗？恳请答复一下，不能用客户端，稍微有点不方便

**Comment by keli** [comment]
你们说的是哪个APP，家庭云吗？这个应该不行的，这docker就只跑了一个迅雷的进程，我也只用得到这个功能，其他的我没有研究。

**Comment by suifengsh** [comment]
是的，就是说家庭云，感谢解答
