### ISSUE TITLE
现在还可以用吗？

### ISSUE THREAD

**Issue by zhongyb** [keli/docker-xiazaibao-xware#6]
我在一台服务器上运行起来了，也成功的找了一个mac，但添加下载后一直没有数据下载，不知道现在还能不能用？

**Comment by keli** [comment]
我一直可以用，离线和高速通道都有速度。你是迅雷会员吗？

![image](https://user-images.githubusercontent.com/329781/70859744-58283c80-1f53-11ea-8745-6e3ee9bfa11f.png)

**Comment by zhongyb** [comment]
不是会员，换一个热门资源就可以下载了，下午那三个都没有下载成功。
